std_msgs/Header header
int32 GPSWeek
float64 GPSTime
float64 Heading
float64 Pitch
float64 Roll
float64 gyroX
float64 gyroY
float64 gyroZ
float64 accX
float64 accY
float64 accZ
float64 Lattitude
float64 Longitude
float64 Altitude
float64 Ve # velocity towards east
float64 Vn # velocity towards north
float64 Vu
float64 Baseline # Velocity of vehicle
int32 NSV1 # number of the settlelites
int32 NSV2
int8 Status
float32 Age
int8 warning




