# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from IntegratedNavigation/IntegratedNavigationMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class IntegratedNavigationMsg(genpy.Message):
  _md5sum = "d81d7ef76c6aee37d26e89632fe99105"
  _type = "IntegratedNavigation/IntegratedNavigationMsg"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float32 GPSWeek
float32 GPSTime
float32 Heading
float32 Pitch
float32 Roll
float32 gyroX
float32 gyroY
float32 gyroZ
float32 accX
float32 accY
float32 accZ
float32 Lattitude
float32 Longitude
float32 Altitude
float32 Ve # velocity towards east
float32 Vn # velocity towards north
float32 Vu
float32 Baseline # Velocity of vehicle
int32 NSV1 # number of the settlelites
int32 NSV2
int8 Status
float32 Age
int8 warning





================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','GPSWeek','GPSTime','Heading','Pitch','Roll','gyroX','gyroY','gyroZ','accX','accY','accZ','Lattitude','Longitude','Altitude','Ve','Vn','Vu','Baseline','NSV1','NSV2','Status','Age','warning']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','int32','int32','int8','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,GPSWeek,GPSTime,Heading,Pitch,Roll,gyroX,gyroY,gyroZ,accX,accY,accZ,Lattitude,Longitude,Altitude,Ve,Vn,Vu,Baseline,NSV1,NSV2,Status,Age,warning

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IntegratedNavigationMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.GPSWeek is None:
        self.GPSWeek = 0.
      if self.GPSTime is None:
        self.GPSTime = 0.
      if self.Heading is None:
        self.Heading = 0.
      if self.Pitch is None:
        self.Pitch = 0.
      if self.Roll is None:
        self.Roll = 0.
      if self.gyroX is None:
        self.gyroX = 0.
      if self.gyroY is None:
        self.gyroY = 0.
      if self.gyroZ is None:
        self.gyroZ = 0.
      if self.accX is None:
        self.accX = 0.
      if self.accY is None:
        self.accY = 0.
      if self.accZ is None:
        self.accZ = 0.
      if self.Lattitude is None:
        self.Lattitude = 0.
      if self.Longitude is None:
        self.Longitude = 0.
      if self.Altitude is None:
        self.Altitude = 0.
      if self.Ve is None:
        self.Ve = 0.
      if self.Vn is None:
        self.Vn = 0.
      if self.Vu is None:
        self.Vu = 0.
      if self.Baseline is None:
        self.Baseline = 0.
      if self.NSV1 is None:
        self.NSV1 = 0
      if self.NSV2 is None:
        self.NSV2 = 0
      if self.Status is None:
        self.Status = 0
      if self.Age is None:
        self.Age = 0.
      if self.warning is None:
        self.warning = 0
    else:
      self.header = std_msgs.msg.Header()
      self.GPSWeek = 0.
      self.GPSTime = 0.
      self.Heading = 0.
      self.Pitch = 0.
      self.Roll = 0.
      self.gyroX = 0.
      self.gyroY = 0.
      self.gyroZ = 0.
      self.accX = 0.
      self.accY = 0.
      self.accZ = 0.
      self.Lattitude = 0.
      self.Longitude = 0.
      self.Altitude = 0.
      self.Ve = 0.
      self.Vn = 0.
      self.Vu = 0.
      self.Baseline = 0.
      self.NSV1 = 0
      self.NSV2 = 0
      self.Status = 0
      self.Age = 0.
      self.warning = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18f2ibfb().pack(_x.GPSWeek, _x.GPSTime, _x.Heading, _x.Pitch, _x.Roll, _x.gyroX, _x.gyroY, _x.gyroZ, _x.accX, _x.accY, _x.accZ, _x.Lattitude, _x.Longitude, _x.Altitude, _x.Ve, _x.Vn, _x.Vu, _x.Baseline, _x.NSV1, _x.NSV2, _x.Status, _x.Age, _x.warning))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 86
      (_x.GPSWeek, _x.GPSTime, _x.Heading, _x.Pitch, _x.Roll, _x.gyroX, _x.gyroY, _x.gyroZ, _x.accX, _x.accY, _x.accZ, _x.Lattitude, _x.Longitude, _x.Altitude, _x.Ve, _x.Vn, _x.Vu, _x.Baseline, _x.NSV1, _x.NSV2, _x.Status, _x.Age, _x.warning,) = _get_struct_18f2ibfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18f2ibfb().pack(_x.GPSWeek, _x.GPSTime, _x.Heading, _x.Pitch, _x.Roll, _x.gyroX, _x.gyroY, _x.gyroZ, _x.accX, _x.accY, _x.accZ, _x.Lattitude, _x.Longitude, _x.Altitude, _x.Ve, _x.Vn, _x.Vu, _x.Baseline, _x.NSV1, _x.NSV2, _x.Status, _x.Age, _x.warning))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 86
      (_x.GPSWeek, _x.GPSTime, _x.Heading, _x.Pitch, _x.Roll, _x.gyroX, _x.gyroY, _x.gyroZ, _x.accX, _x.accY, _x.accZ, _x.Lattitude, _x.Longitude, _x.Altitude, _x.Ve, _x.Vn, _x.Vu, _x.Baseline, _x.NSV1, _x.NSV2, _x.Status, _x.Age, _x.warning,) = _get_struct_18f2ibfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_18f2ibfb = None
def _get_struct_18f2ibfb():
    global _struct_18f2ibfb
    if _struct_18f2ibfb is None:
        _struct_18f2ibfb = struct.Struct("<18f2ibfb")
    return _struct_18f2ibfb
