(cl:in-package IntegratedNavigation-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPSWEEK-VAL
          GPSWEEK
          GPSTIME-VAL
          GPSTIME
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          GYROX-VAL
          GYROX
          GYROY-VAL
          GYROY
          GYROZ-VAL
          GYROZ
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          LATTITUDE-VAL
          LATTITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          BASELINE-VAL
          BASELINE
          NSV1-VAL
          NSV1
          NSV2-VAL
          NSV2
          STATUS-VAL
          STATUS
          AGE-VAL
          AGE
          WARNING-VAL
          WARNING
))